
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'D206C0CC01D0B0F52BBAFB171C4B01FE'
    
_lr_action_items = {'BOOK':([0,],[12,]),'FLY':([0,],[1,]),'VISIT':([0,],[13,]),'DAYS':([28,],[33,]),'STRING':([1,3,5,8,9,13,16,20,22,23,],[22,23,24,25,26,27,28,29,30,31,]),'$end':([2,4,6,7,10,11,12,14,15,17,18,19,21,25,26,27,29,30,31,33,34,],[-3,-9,-1,-10,-7,-12,-20,-8,-2,-5,-4,0,-6,-18,-17,-19,-15,-14,-11,-16,-13,]),'FLIGHTS':([0,],[5,]),'CREATEPACKAGE':([0,],[3,]),'RESERVE':([0,],[16,]),'CARS':([0,],[9,]),'HOTELS':([0,],[20,]),'DESTINATIONS':([0,],[11,]),'DATE':([24,32,],[32,34,]),'TOURS':([0,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement_book':([0,],[7,]),'statement_fly':([0,],[18,]),'statement_flights':([0,],[2,]),'statement':([0,],[19,]),'statement_visit':([0,],[4,]),'statement_reserve':([0,],[21,]),'statement_tours':([0,],[14,]),'statement_destinations':([0,],[15,]),'statement_cars':([0,],[10,]),'statement_hotels':([0,],[17,]),'statement_createpackage':([0,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> statement_createpackage','statement',1,'p_statement','VoyageYacc.py',15),
  ('statement -> statement_destinations','statement',1,'p_statement','VoyageYacc.py',16),
  ('statement -> statement_flights','statement',1,'p_statement','VoyageYacc.py',17),
  ('statement -> statement_fly','statement',1,'p_statement','VoyageYacc.py',18),
  ('statement -> statement_hotels','statement',1,'p_statement','VoyageYacc.py',19),
  ('statement -> statement_reserve','statement',1,'p_statement','VoyageYacc.py',20),
  ('statement -> statement_cars','statement',1,'p_statement','VoyageYacc.py',21),
  ('statement -> statement_tours','statement',1,'p_statement','VoyageYacc.py',22),
  ('statement -> statement_visit','statement',1,'p_statement','VoyageYacc.py',23),
  ('statement -> statement_book','statement',1,'p_statement','VoyageYacc.py',24),
  ('statement_createpackage -> CREATEPACKAGE STRING STRING','statement_createpackage',3,'p_statement_createpackage','VoyageYacc.py',30),
  ('statement_destinations -> DESTINATIONS','statement_destinations',1,'p_statement_destinations','VoyageYacc.py',36),
  ('statement_flights -> FLIGHTS STRING DATE DATE','statement_flights',4,'p_statement_flights','VoyageYacc.py',43),
  ('statement_fly -> FLY STRING STRING','statement_fly',3,'p_statement_fly','VoyageYacc.py',48),
  ('statement_hotels -> HOTELS STRING','statement_hotels',2,'p_statement_hotels','VoyageYacc.py',54),
  ('statement_reserve -> RESERVE STRING DAYS','statement_reserve',3,'p_statement_reserve','VoyageYacc.py',60),
  ('statement_cars -> CARS STRING','statement_cars',2,'p_statement_cars','VoyageYacc.py',66),
  ('statement_tours -> TOURS STRING','statement_tours',2,'p_statement_tours','VoyageYacc.py',72),
  ('statement_visit -> VISIT STRING','statement_visit',2,'p_statement_visit','VoyageYacc.py',78),
  ('statement_book -> BOOK','statement_book',1,'p_statement_book','VoyageYacc.py',84),
]
