
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '6271D98268BE0288BF19380414B92B11'
    
_lr_action_items = {'BOOK':([0,],[14,]),'AIRLINE':([27,],[34,]),'STAY':([0,],[2,]),'CARS':([0,],[3,]),'CREATEPACKAGE':([0,],[4,]),'DATE':([28,35,],[35,38,]),'NAME':([4,26,],[26,33,]),'DESTINATIONS':([0,],[16,]),'FLY':([0,],[7,]),'$end':([1,5,6,9,10,12,13,14,15,16,17,18,20,21,24,25,30,32,33,34,36,37,38,],[-7,-9,-3,0,-11,-8,-6,-22,-4,-13,-1,-2,-5,-10,-18,-19,-20,-16,-12,-15,-17,-21,-14,]),'RENTAL':([11,],[29,]),'FLIGHTS':([0,],[8,]),'HOTEL':([2,],[24,]),'DAYS':([29,],[36,]),'DESTINATION':([3,7,8,19,22,23,],[25,27,28,30,31,32,]),'VISIT':([0,],[22,]),'TOURS':([0,],[19,]),'HOTELS':([0,],[23,]),'RESERVE':([0,],[11,]),'TOUR':([31,],[37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement_reserve':([0,],[13,]),'statement_stay':([0,],[1,]),'statement_fly':([0,],[15,]),'statement_createpackage':([0,],[17,]),'statement_destinations':([0,],[18,]),'statement':([0,],[9,]),'statement_hotels':([0,],[20,]),'statement_book':([0,],[10,]),'statement_flights':([0,],[6,]),'statement_visit':([0,],[21,]),'statement_tours':([0,],[5,]),'statement_cars':([0,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> statement_createpackage','statement',1,'p_statement','VoyageYacc.py',15),
  ('statement -> statement_destinations','statement',1,'p_statement','VoyageYacc.py',16),
  ('statement -> statement_flights','statement',1,'p_statement','VoyageYacc.py',17),
  ('statement -> statement_fly','statement',1,'p_statement','VoyageYacc.py',18),
  ('statement -> statement_hotels','statement',1,'p_statement','VoyageYacc.py',19),
  ('statement -> statement_reserve','statement',1,'p_statement','VoyageYacc.py',20),
  ('statement -> statement_stay','statement',1,'p_statement','VoyageYacc.py',21),
  ('statement -> statement_cars','statement',1,'p_statement','VoyageYacc.py',22),
  ('statement -> statement_tours','statement',1,'p_statement','VoyageYacc.py',23),
  ('statement -> statement_visit','statement',1,'p_statement','VoyageYacc.py',24),
  ('statement -> statement_book','statement',1,'p_statement','VoyageYacc.py',25),
  ('statement_createpackage -> CREATEPACKAGE NAME NAME','statement_createpackage',3,'p_statement_createpackage','VoyageYacc.py',31),
  ('statement_destinations -> DESTINATIONS','statement_destinations',1,'p_statement_destinations','VoyageYacc.py',37),
  ('statement_flights -> FLIGHTS DESTINATION DATE DATE','statement_flights',4,'p_statement_flights','VoyageYacc.py',43),
  ('statement_fly -> FLY DESTINATION AIRLINE','statement_fly',3,'p_statement_fly','VoyageYacc.py',49),
  ('statement_hotels -> HOTELS DESTINATION','statement_hotels',2,'p_statement_hotels','VoyageYacc.py',55),
  ('statement_reserve -> RESERVE RENTAL DAYS','statement_reserve',3,'p_statement_reserve','VoyageYacc.py',61),
  ('statement_stay -> STAY HOTEL','statement_stay',2,'p_statement_stay','VoyageYacc.py',67),
  ('statement_cars -> CARS DESTINATION','statement_cars',2,'p_statement_cars','VoyageYacc.py',73),
  ('statement_tours -> TOURS DESTINATION','statement_tours',2,'p_statement_tours','VoyageYacc.py',79),
  ('statement_visit -> VISIT DESTINATION TOUR','statement_visit',3,'p_statement_visit','VoyageYacc.py',85),
  ('statement_book -> BOOK','statement_book',1,'p_statement_book','VoyageYacc.py',91),
]
